//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ws.Fus.UI.Assets.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ws.Fus.UI.Assets.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string HDR_DATE {
            get {
                return ResourceManager.GetString("HDR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HDR_ID {
            get {
                return ResourceManager.GetString("HDR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All.
        /// </summary>
        public static string HDR_LOAD_ALL {
            get {
                return ResourceManager.GetString("HDR_LOAD_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HDR_NAME {
            get {
                return ResourceManager.GetString("HDR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Lateral.
        /// </summary>
        public static string IDS_LBL_BI_LATERAL {
            get {
                return ResourceManager.GetString("IDS_LBL_BI_LATERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Location.
        /// </summary>
        public static string IDS_LBL_BRAIN_SIDE {
            get {
                return ResourceManager.GetString("IDS_LBL_BRAIN_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string IDS_LBL_DEVICE {
            get {
                return ResourceManager.GetString("IDS_LBL_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Exam Information.
        /// </summary>
        public static string IDS_LBL_EXAM_INFO {
            get {
                return ResourceManager.GetString("IDS_LBL_EXAM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam#:.
        /// </summary>
        public static string IDS_LBL_EXAM_N {
            get {
                return ResourceManager.GetString("IDS_LBL_EXAM_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string IDS_LBL_LEFT {
            get {
                return ResourceManager.GetString("IDS_LBL_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC-PC PLANE.
        /// </summary>
        public static string IDS_LBL_MENU_AC_PC {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_AC_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIBRATION.
        /// </summary>
        public static string IDS_LBL_MENU_CALIBRATION {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        public static string IDS_LBL_MENU_DATABASE {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQA.
        /// </summary>
        public static string IDS_LBL_MENU_DQA {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_DQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPR REVIEW.
        /// </summary>
        public static string IDS_LBL_MENU_NPR {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN.
        /// </summary>
        public static string IDS_LBL_MENU_PLANNING_SCAN {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_PLANNING_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREPARATION.
        /// </summary>
        public static string IDS_LBL_MENU_PREPLANNING {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_PREPLANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION.
        /// </summary>
        public static string IDS_LBL_MENU_REGISTRATION {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        public static string IDS_LBL_MENU_REPORT {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCREENING.
        /// </summary>
        public static string IDS_LBL_MENU_SCREENING {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_SCREENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string IDS_LBL_MENU_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET-UP.
        /// </summary>
        public static string IDS_LBL_MENU_SETUP {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERAPY.
        /// </summary>
        public static string IDS_LBL_MENU_SURGICAL {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_SURGICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SONICATE.
        /// </summary>
        public static string IDS_LBL_MENU_SURGICAL_DQA {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_SURGICAL_DQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGET &amp; SAVE.
        /// </summary>
        public static string IDS_LBL_MENU_TARGET_SAVE {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_TARGET_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGETING.
        /// </summary>
        public static string IDS_LBL_MENU_TARGETING {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_TARGETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREATMENT.
        /// </summary>
        public static string IDS_LBL_MENU_TREATMENT {
            get {
                return ResourceManager.GetString("IDS_LBL_MENU_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRI.
        /// </summary>
        public static string IDS_LBL_MRI {
            get {
                return ResourceManager.GetString("IDS_LBL_MRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string IDS_LBL_NO {
            get {
                return ResourceManager.GetString("IDS_LBL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string IDS_LBL_OK {
            get {
                return ResourceManager.GetString("IDS_LBL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID:.
        /// </summary>
        public static string IDS_LBL_PATIENT_ID {
            get {
                return ResourceManager.GetString("IDS_LBL_PATIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name:.
        /// </summary>
        public static string IDS_LBL_PATIENT_NAME {
            get {
                return ResourceManager.GetString("IDS_LBL_PATIENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN.
        /// </summary>
        public static string IDS_LBL_PLANNING {
            get {
                return ResourceManager.GetString("IDS_LBL_PLANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        public static string IDS_LBL_QUIT {
            get {
                return ResourceManager.GetString("IDS_LBL_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT DQA.
        /// </summary>
        public static string IDS_LBL_QUIT_DQA {
            get {
                return ResourceManager.GetString("IDS_LBL_QUIT_DQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END
        ///TREATMENT.
        /// </summary>
        public static string IDS_LBL_QUIT_TREATMENT {
            get {
                return ResourceManager.GetString("IDS_LBL_QUIT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string IDS_LBL_RIGHT {
            get {
                return ResourceManager.GetString("IDS_LBL_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treating Physician.
        /// </summary>
        public static string IDS_LBL_TRTM_PHYSICIAN {
            get {
                return ResourceManager.GetString("IDS_LBL_TRTM_PHYSICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference Profile.
        /// </summary>
        public static string IDS_LBL_TRTM_PROTOCOL {
            get {
                return ResourceManager.GetString("IDS_LBL_TRTM_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start DQA.
        /// </summary>
        public static string IDS_LBL_TRTM_START_DQA {
            get {
                return ResourceManager.GetString("IDS_LBL_TRTM_START_DQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pre-Planning.
        /// </summary>
        public static string IDS_LBL_TRTM_START_SESSION {
            get {
                return ResourceManager.GetString("IDS_LBL_TRTM_START_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Treatment.
        /// </summary>
        public static string IDS_LBL_TRTM_START_TREATMENT {
            get {
                return ResourceManager.GetString("IDS_LBL_TRTM_START_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string IDS_LBL_USER_NAME {
            get {
                return ResourceManager.GetString("IDS_LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water System.
        /// </summary>
        public static string IDS_LBL_WATER_SYSTEM {
            get {
                return ResourceManager.GetString("IDS_LBL_WATER_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string IDS_LBL_YES {
            get {
                return ResourceManager.GetString("IDS_LBL_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen is available.
        /// </summary>
        public static string IDS_TT_STATE_AVAILABLE {
            get {
                return ResourceManager.GetString("IDS_TT_STATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen is available and waiting for activity.
        /// </summary>
        public static string IDS_TT_STATE_CALL_TO_ACTION {
            get {
                return ResourceManager.GetString("IDS_TT_STATE_CALL_TO_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen is completed.
        /// </summary>
        public static string IDS_TT_STATE_COMPLETED {
            get {
                return ResourceManager.GetString("IDS_TT_STATE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen is unavailable.
        /// </summary>
        public static string IDS_TT_STATE_UNAVAILABLE {
            get {
                return ResourceManager.GetString("IDS_TT_STATE_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ).
        /// </summary>
        public static string INFO_CLOSE_BRACKET {
            get {
                return ResourceManager.GetString("INFO_CLOSE_BRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string INFO_DURATION {
            get {
                return ResourceManager.GetString("INFO_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string INFO_LIMIT {
            get {
                return ResourceManager.GetString("INFO_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string INFO_OFF {
            get {
                return ResourceManager.GetString("INFO_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string INFO_ON {
            get {
                return ResourceManager.GetString("INFO_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string INFO_OPEN_BRACKET {
            get {
                return ResourceManager.GetString("INFO_OPEN_BRACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string INFO_PATIENT_ID {
            get {
                return ResourceManager.GetString("INFO_PATIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string INFO_PATIENT_NAME {
            get {
                return ResourceManager.GetString("INFO_PATIENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string INFO_POWER {
            get {
                return ResourceManager.GetString("INFO_POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string INFO_TARGET {
            get {
                return ResourceManager.GetString("INFO_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string INFO_WARNING {
            get {
                return ResourceManager.GetString("INFO_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        public static string LBL_APPLY_CHANGES {
            get {
                return ResourceManager.GetString("LBL_APPLY_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LBL_CANCEL {
            get {
                return ResourceManager.GetString("LBL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string LBL_DEFAULT {
            get {
                return ResourceManager.GetString("LBL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string LBL_DISCARD_CHANGES {
            get {
                return ResourceManager.GetString("LBL_DISCARD_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LBL_LOAD {
            get {
                return ResourceManager.GetString("LBL_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Pre-Treatment Plan.
        /// </summary>
        public static string LBL_LOAD_PREPLAN {
            get {
                return ResourceManager.GetString("LBL_LOAD_PREPLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LBL_PROFILE {
            get {
                return ResourceManager.GetString("LBL_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHUTDOWN.
        /// </summary>
        public static string LBL_SHUTDOWN {
            get {
                return ResourceManager.GetString("LBL_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string LBL_SYSTEM {
            get {
                return ResourceManager.GetString("LBL_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TT_CLOSE {
            get {
                return ResourceManager.GetString("TT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string TT_ENABLE {
            get {
                return ResourceManager.GetString("TT_ENABLE", resourceCulture);
            }
        }
    }
}
